### ISSUE TITLE
Support Preview for animated .vtf

### ISSUE THREAD

**Issue by SupinePandora43** [Gira-X/VMT-Editor#69]
# Steps To Reproduce
1. open any animated .vtf texture
# Excepted Result
animated preview
# Actual Result
static texture

**Comment by Gira-X** [comment]
This is not working because `VMT Editor` uses [VTFCmd] internally to convert the `.vtf` files to `.png` for display which does not have animation info.

And [VTFCmd] does not allow exporting a `.vtf` file to an image format with animation info.
Those are the supported conversion options from their page:

> Convert .vtf files to .bmp, .jpg, .png and .tga files.

---

Yes, it would be amazing to have animated preview in `VMT Editor` but it is not possible right now :(

[VTFCmd]: http://nemesis.thewavelength.net/index.php?p=40
